name: Publish NuGet Package

on:
  push:
    branches:
      - master
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Extract version from .csproj
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=<Version>).*?(?=</Version>)' StackExchange.Redis.DistributedRepository/StackExchange.Redis.DistributedRepository.csproj)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if version exists on NuGet
        id: check_nuget
        run: |
          if curl --silent --fail --head "https://www.nuget.org/api/v2/package/YourPackageName/$VERSION"; then
            echo "VERSION_EXISTS=true" >> $GITHUB_ENV
          else
            echo "VERSION_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Pack
        if: env.VERSION_EXISTS == 'false'
        run: dotnet pack --configuration Release --no-build --output nupkg

      - name: Push to NuGet
        if: env.VERSION_EXISTS == 'false'
        run: dotnet nuget push nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
